Livewire обновлен до версии 3
moad-dev/otzyvus pull request #134
Opened 2023-09-28 12:25 UTC by bulatovv

:tada: :tada: :tada:

2023-09-28 13:20 UTC, bulatovv commented
После мерджа не забудьте поставить пакеты (composer, npm) и удалить кжш вьюшек (`artisan view:clear`)

2023-09-28 16:34 UTC, nizamovtimur reviewed
см. комментарии к коду + если выбрать на главной фильтры по майнорам и обновить страницу, слетит цвет

2023-09-28 16:34 UTC, nizamovtimur commented on app/Livewire/Feedbacks/AbstractSearchFeedbacks.php
у элективов номер страницы в get-запросе не фигурирует, а тут остался

2023-09-28 16:34 UTC, nizamovtimur commented on app/Livewire/SelectNotifications.php
in_array(): Argument #2 ($haystack) must be of type array, Illuminate\Support\Collection given

2023-09-28 16:36 UTC, nizamovtimur commented on app/Livewire/Feedbacks/AbstractSearchFeedbacks.php
на странице с пользователями в админке тоже

2023-10-03 07:36 UTC, nizamovtimur requested changes
Всё хорошо, но куда-то пропало оповещение об оставлении жалобы на странице электива

TODO: создать ищью о баге лайввайра с пагингацией

2023-10-04 08:39 UTC, nizamovtimur approved these changes
L G T M !!!

2023-10-04 08:39 UTC, merged